### ISSUE TITLE
feature request: support for pnpx and pnpm

### ISSUE THREAD

**Issue by mrsauravsahu** [AdonisCommunity/create-adonis-ts-app#13]
## Why this feature is required (specific use-cases will be appreciated)?
- Projects using `pnpm` workspaces currently can't use the starter template as the installer uses npm to install the dependencies.
- The npm dependency requirements (the requirements are not getting installed with `pnpm import`

## Have you tried any other workarounds?
- Currently, to make it work, I'm having to manually install the required packages to run the server in my devDependencies.
An example project I've fixed with the workaround is here https://github.com/mrsauravsahu/mrsauravsahu.github.io - you can check the `@mrsauravsahu/blogs` package

## Are you willing to work on it with little guidance?
- Would love to, but this depends on how complex the solution turns out to be. The solution could also be also related to how pnpm handles dependencies

---

## Steps to reproduce
1. Create a start project (`pnpx create-adonis-ts-app sample`)
2. Remove npm dependencies (`rm -rf node_modules`)
3. Import dependencies with pnpm (`pnpm import`)
4. Install dependencies with pnpm (`pnpm i`)

The start command `node ace serve --watch` should give you an error like shown.

<img width="785" alt="Screenshot 2020-07-11 at 19 35 51" src="https://user-images.githubusercontent.com/9134050/87225892-e6f81d00-c3ad-11ea-8404-83b099de963a.png">

The workaround is to carefully install package into devDependencies with `pnpm i -D <package-name>`

**Comment by RomainLanz** [comment]
Hey @mrsauravsahu! 👋 

AdonisJS does not work yet with `pnpm` with their way of installing dependencies.
I'd recommend installing the dependencies using the flag`--shamefully-hoist` to make it work seamlessly with `pnpm`.

```bash
pnpm i --shamefully-hoist
```

**Comment by mrsauravsahu** [comment]
This works nicely for now. Thanks @RomainLanz.
Closing this.
