### ISSUE TITLE
script is not function

### ISSUE THREAD

**Issue by parmatmasharmag79** [AdonisCommunity/create-adonis-ts-app#15]
Hi, 

while creating application using typescript.
I am facing problem while using script tag to load any external js which is declared in public folder but it always says script is not function. please guide me where i need to configure to access script tag.
Ex - 
suppose i  have created example.js file in public folder but while using in view edge file - {{script('example')}}
it not work, script is not function.

**Comment by RomainLanz** [comment]
Hey @parmatmasharmag79! 👋 

Those helpers don't exist anymore in AdonisJS 5.
If you want to load a JS file or a CSS file simply use the correct HTML tag.

Also take not this is not the correct repository to ask question about AdonisJS, please, use [our Discussion Platform](https://github.com/adonisjs/core/discussions) next time.
