### ISSUE TITLE
Simply doesn't work

### ISSUE THREAD

**Issue by DrummerSi** [AdonisCommunity/create-adonis-ts-app#2]
#### Node.js and npm version
NPM: 6.7, Node: 11.15, Yarn: 1.17

#### Sample Code (to reproduce the issue)
yarn create adonis-ts-app yardstick
yarn start

## Description
Attempting to run the template using "yarn start" or "npm start" returns the error message:
**Make sure you are inside an adonisjs app to start the server**

**Comment by thetutlage** [comment]
Closing, since the project is meant to used right now, unless the documentation is out
