### ISSUE TITLE
Unexpected token '.'

### ISSUE THREAD

**Issue by kursatsen-kitapify** [AdonisCommunity/create-adonis-ts-app#21]
I cant use npx create-adonis-ts-app and yarn. Help me please.
![image](https://user-images.githubusercontent.com/77462925/112281477-23974a80-8c97-11eb-9a3e-da86316b444f.png)

**Comment by ignatevdev** [comment]
Having the same issue on different platforms: Mac / Windows / Windows (WSL)

![image](https://user-images.githubusercontent.com/8458382/112370222-2bcea480-8cee-11eb-8978-633d50d483ce.png)

**Comment by ignatevdev** [comment]
This is where the error comes from:
![image](https://user-images.githubusercontent.com/8458382/112371056-3b022200-8cef-11eb-81c3-9caf72b75044.png)

**Comment by ignatevdev** [comment]
Alright, the error happens because one of the dependencies uses optional chaining syntax which is not supported in old versions of node.

Updating nodejs to the latest stable fixes this issue.
