### ISSUE TITLE
"npm install failed" with eslint - works with yarn

### ISSUE THREAD

**Issue by maxgalbu** [AdonisCommunity/create-adonis-ts-app#33]
## Package version
@latest

## Node.js and npm version
npm: 7.18.1
node: v16.4.2

## Sample Code (to reproduce the issue)
1. npm init adonis-ts-app hello-world
2. api project
3. yes to eslint
4. yes to prettier

output:

```
    _       _             _         _
   / \   __| | ___  _ __ (_)___    | |___
  / _ \ / _` |/ _ \| '_ \| / __|_  | / __|
 / ___ \ (_| | (_) | | | | \__ \ |_| \__ \
/_/   \_\__,_|\___/|_| |_|_|___/\___/|___/


CUSTOMIZE PROJECT
❯ Select the project structure · api
❯ Enter the project name · hello-world
❯ Setup eslint? (y/N) · true
❯ Setup prettier? (y/N) · true

RUNNING TASKS
❯ Scaffold project 48 ms
❯ Install dependencies 1.28 s
  npm install failed
❯ Configure installed packages

[ error ]  Unable to create project. Cleaning up
```

It finishes correctly if I don't install eslint + prettier

**Comment by thetutlage** [comment]
Fixed here. https://github.com/adonisjs-community/create-adonis-ts-app/commit/f16bed07022d3d657cc9b1dfd29f71c1cfe34806

Most of the eslint plugins are not compatible with eslint 8.0 yet. Hence, npm installation fails because of unmet peer dependency
